services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: your_database_name
    volumes:
      - ./API:/app

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  #angular:
  #  build:
  #    context: ./chiro-website  # Context for the Angular app
  #    dockerfile: Dockerfile  # Ensure this matches the Angular Dockerfile name
  #  container_name: angular-app
  #  ports:
  #    - "4200:80"  # Map port 4200 on the host to port 80 in the container

volumes:
  db_data:
