services:
  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chiro-website
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Node.js API
  api:
    build:
      context: ./API  # Path to your Node.js API folder
      dockerfile: Dockerfile
    container_name: node_api
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: chiro-website
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network

  # Angular Web App
  angular:
    build:
      context: ./chiro-website  # Path to your Angular app folder
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - app-network

# Volumes for persistent storage
volumes:
  mysql_data:

# Network for inter-service communication
networks:
  app-network:
