services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persisting the data to a volume

  api:
    build: 
      context: .
      dockerfile: ./API/dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db  # Hostname of MySQL container
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: your_database_name
    volumes:
      - .:/app
    command: "node server.js"  # Adjust if your start script is different

  angular-app:
    build:
      context: .
      dockerfile: ./chiro-website/dockerfile
    container_name: angular-app
    ports:
      - '4200:4200'
    volumes:
      - ./:/angular-app
    environment:
      - STYLE=css
    depends_on:
      - db  
      - api

volumes:
  db_data:
