FROM node:18.13.0 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm instal -g @angular/cli

COPY . .

RUN ng build --configuration

FROM nginx:latest
COPY --from=build app/dist/aftas-angular /usr/share/nginx/html

EXPOSE 90